# Site setings
name: 'Bobby Hamilton\`s Blog'
description: 'All things product, marketing, design and software. From the mind of Bobby Hamilton'
meta_description: 'Bobby Hamilton, product manager, Toronto, software'
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
baseurl: 
production_url: https://horace.netlify.com/
disqus: 'justgoodthemes'
mailchimp_url: '//justgoodthemes.us3.list-manage.com/subscribe/post?u=78f1bab16028354caeb23aecd&amp;id=4a7330d117'
cover_image: bc_1.jpg
# Add your GA Tracking Id
ga_analytics: 


# Author
author:
  name: 'Bobby Hamilton'
  image: 'authorimage.jpg'
  greetings: 'Hi there!'
  description: "My name is Bobby Hamilton. I'm a product manager based in Toronto, Canada."
  bio: 'Bobby is a designer, software engineer, product manager and photographer.'

# Contact form setings
email: youremail@email.com
contact_page_description: "Horace theme comes with a contact form built-in. You can use this form with Formspree service and get up to 50 submissions for free. Also, you can easily switch to another service if you want."
thankyou_page_description: "Your message has been successfully sent. We will contact you very soon!"

# Social links
twitter: 'BobHami'
facebook: 'username'
github: 'bobhami'
codepen: 'username'
medium: '@b0bhamilton'
instagram: 'username'
linkedin: 'b0bhamilton'
producthunt: '@username'

# Navigation
navigation:
  - text: About
    url: /about
  - text: Style Guide
    url: /style-guide
  - text: Contact Me
    url: /contact

# Required Plugins
plugins_dir:
  - jekyll-paginate
  - jekyll-tagsgenerator
  - jekyll-seo-tag
  - jekyll-sitemap

# Pagination
paginate: 5
paginate_path: /page:num/

# Permalinks
permalink: /:title

# Other
markdown: kramdown

# Sass
sass:
  sass_dir: _sass
  style: compressed
